# Generated by Django 5.2.1 on 2025-08-10 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shirt',
        ),
    ]
