# Generated by Django 5.2.1 on 2025-08-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_shirt_is_bestseller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('brand', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
