# Generated by Django 5.2.1 on 2025-08-10 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
