# Generated by Django 5.2.1 on 2025-08-10 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_category_delete_shirt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
