# Generated by Django 5.2.1 on 2025-08-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='suggestions',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
